### ISSUE TITLE
Did you consider the use of GraphFrames instead of GraphX?

### ISSUE THREAD

**Issue by mkarmona** [ma581/ot-connections#1]
[GraphFrames](https://graphframes.github.io/graphframes/docs/_site/index.html)

**Comment by ma581** [comment]
Yes, I did, especially since they have a Python API and GraphX does not. I think they also have a feature called "Motif finding" which looked very powerful. 

Spark is still very new to me and so I wasn't sure how optimised/mature Graphrames was. I decided to use GraphX as it was native to Spark, though that did mean additional work on my part to convert data frames to graph structures.

**Comment by mkarmona** [comment]
thanks for your prompt response.
